### ISSUE TITLE
[CLI] Supress pinentry GTK warnings

### ISSUE THREAD

**Issue by seveneightn9ne** [seveneightn9ne/hashpass#10]
I'm seeing: 
`(pinentry:2909): Gtk-WARNING **: Theme directory 64/apps of theme Numix has no size field`

**Comment by seveneightn9ne** [comment]
@mlsteele where did you get pinentry from? Having trouble googling for it

**Comment by mlsteele** [comment]
I'm guessing it's a GPG dep. I can deal with this issue if you're not already on it.

**Comment by seveneightn9ne** [comment]
Sure, go for it

**Comment by seveneightn9ne** [comment]
Thanks!
